version: "3.11"

services:
  web:
    build: ./
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
